version: "3"
services: 
  mongodb:
    container_name: mongodb-container
    image: mongo:4
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-api
    restart: always
    command: npm run debug start
    volumes: 
      - ./dist:/usr/src/clean-api/dist
      - ./package.json:/usr/src/clean-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongodb